export default [{
  id: 1,
  userName: 'Rodney Wright',
  userScore: 'A',
  amountNeeded: '123.45 USD',
  time: '1 Month',
  percentFunded: '47%',
  percentNeeded: '53%',
}, {
  id: 2,
  userName: 'Cals Cunningham',
  userScore: 'D',
  amountNeeded: '123.45 USD',
  time: '1 Month',
  percentFunded: '47%',
  percentNeeded: '53%',
}, {
  id: 3,
  userName: 'Kyle Spencer',
  userScore: 'B',
  amountNeeded: '123.45 USD',
  time: '1 Month',
  percentFunded: '47%',
  percentNeeded: '53%',
}];
