export default [{
  id: 1,
  userName: 'Rodney Wright',
  userScore: 'A',
  amountNeeded: '123.45 USD',
  time: '1 Month',
  percentFunded: '47%',
  percentNeeded: '53%',
  shortDesc: 'My business investment',
  currentRate: '100 BTC',
  rate: '1.5%',
  apr: '15%',
  earned: '1.00 BTC',
}, {
  id: 2,
  userName: 'Cals Cunningham',
  userScore: 'D',
  amountNeeded: '123.45 USD',
  time: '1 Month',
  percentFunded: '47%',
  percentNeeded: '53%',
  shortDesc: 'I would like to open 2nd Google',
  currentRate: '100 BTC',
  rate: '1.6%',
  apr: '16%',
  earned: '2.00 BTC',
}, {
  id: 3,
  userName: 'Kyle Spencer',
  userScore: 'B',
  amountNeeded: '123.45 USD',
  time: '1 Month',
  percentFunded: '47%',
  percentNeeded: '53%',
  shortDesc: 'I would like to open 3nd Google',
  currentRate: '101 BTC',
  rate: '1.7%',
  apr: '17%',
  earned: '3.00 BTC',
}];
